development:
    adapter: mysql
    database: nines_development
    username: root
    password: 
    host: localhost
    
test:
    adapter: mysql
    database: nines_test
    username: root
    password: 
    host: localhost

production:
    adapter: mysql
    database: nines_production
    #database: nines_development
    username: root
    password:
    host: localhost
    
# In-memory SQLite 3 database.  Useful for tests.
sqlite3_in_memory_example:
  adapter: sqlite3
  dbfile: ":memory:"

#Java constants
sqlUser: root
sqlPass: 
sqlServer: 
smtpServer: 
smtpFromEmail: 
smtpPassword: 
smtpPort: 
solrUrl: http://localhost:8983/solr/update
rails_root: localhost:3000
dir1: 
dir2: 
tempdir: 