development:
    adapter: mysql
    database: nines_development
    username: root
    password: 
    host: localhost
    solrUrl: http://localhost:8983/solr/update
    
test:
    adapter: mysql
    database: nines_test
    username: root
    password: 
    host: localhost
    solrUrl: http://localhost:8983/solr/update

production:
  adapter: mysql
  database: nines_development
  username: root
  password: 
  host: localhost
  solrUrl: http://localhost:8983/solr/update
    
# In-memory SQLite 3 database.  Useful for tests.
sqlite3_in_memory_example:
  adapter: sqlite3
  dbfile: ":memory:"

#Java constants
java_constants:
  smtpServer: null
  smtpFromEmail: null
  smtpPassword: null
  smtpPort: 465
  rails_root: localhost:3000
  dir1: /ninestestA
  dir2: /ninestestB
  tempdir: /tmp