development:
    adapter: mysql
    database: nines_development
    username: root
    password: 
    host: localhost
    
test:
    adapter: mysql
    database: nines_test
    username: root
    password: 
    host: localhost

production:
  adapter: mysql
  database: nines_production
  username: root
  password: 
  host: localhost

staging:
  adapter: mysql
  database: nines_development
  username: root
  password: 
  host: localhost
